### ISSUE TITLE
https://api.exchangerate.host/ is down

### ISSUE THREAD

**Issue by heratyian** [appdev-projects/sinatra-exchange-rates#2]
Just an FYI. Will probably resolve itself.

**Comment by bpurinton** [comment]
Oy. Thanks. We'll need to monitor the sitch closely. Or change projects accordingly.

**Comment by bpurinton** [comment]
Bet it'll resolve soon. A lotta folks are affected: https://github.com/Formicka/exchangerate.host/issues/236

**Comment by heratyian** [comment]
also GitHub repo lessons w/ issues ftw 🥇

**Comment by bpurinton** [comment]
[It's been resolved](https://github.com/Formicka/exchangerate.host/issues/236#issuecomment-1731955679)
